### ISSUE TITLE
Duplicate sensor error when multiple inverters

### ISSUE THREAD

**Issue by Gunth** [kellerza/pysma#16]
Don't know if i need to logge issue there or in the issue tracker of home assistant, i made both to be sure :-)

I have multiple inverter and ma configuration was working with the previous version 8.5, since the new release 0.86.1 version I have a exception saying that 2 sensors with the same name are present.
With the previous version the sensors was generated like this for instence : total_yield, total_yield_2 seems that it's not the case anymore.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 344, in _async_add_entity
>     raise HomeAssistantError(msg)
> homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.daily_yield. Platform sma does not generate unique IDs

**Comment by kellerza** [comment]
This specific issue is related to the HASS platform and will work on it there. Best to just CC: me in the Issue there
