### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by bccrew** [kellerza/pysma#27]
Hi,

I was wondering if you would like to consider adding mqtt support. It's becoming a very common standard in home automation and it would open doors in adding support for other systems like Domoticz or Openhab for monitoring SMA inverters.

Sending value's as mqtt payloads to a broker would suffice.

Thanks!

**Comment by kellerza** [comment]
This is not something I am specifically interested in and I see it as quite a lot of work

Components required:

- some way to configure the SMA inverter. sensors and mqtt parameters/topics (probably yaml file)
- instructions on running this/ dockerfile to run this for (unraid, hass.io or you favourite NAS)
- document all of this
- be ready for question on how to configure mqtt on x/y home automation platform
- discovery for x/y home automation platform

The home assistant component gives you all this and a better experience in my view (it also has a very helpful community)

Feel free to build this using this library, we can even include/PR that into this library if you are willing to help
