### ISSUE TITLE
daily_yield

### ISSUE THREAD

**Issue by jensschneider** [kellerza/pysma#47]
I think the current value of `daily_yield` is the sum of yesterday and today.

**Comment by kellerza** [comment]
@jensschneider I cannot comment on the actual content of individual sensors, but have found that in many cases it is more reliable to use a higher layer to calculate running totals. 

Recently [documented](https://github.com/kellerza/hassio-sma-em/blob/main/sma-em/DOCS.md#home-assistant-filters--utility-meter) such an approach for the energy meter - in the SMA energy meter plugin for HomeAssistant
