### ISSUE TITLE
Statistic entities home assistant

### ISSUE THREAD

**Issue by clasheleander** [kellerza/pysma#83]
Any plans for adding support for entities in the new Energy thing in homeassistant?
Thanks!

https://www.home-assistant.io/more-info/statistics/

**Comment by rklomp** [comment]
Should be supported already. I am using it without issues.

**Comment by clasheleander** [comment]
Ok, Strange, i disabled all yaml config for SMA, uninstalled the integration and installed it again. the Energy integration still not showing correct entities from drop down.

![grid](https://user-images.githubusercontent.com/69042470/128626458-74e44f1a-a65b-4ecb-80f6-600f0831de12.JPG)
![grid2](https://user-images.githubusercontent.com/69042470/128626461-01d4fe8b-988d-4303-a1f5-4e8c00e56eb0.JPG)
![solar](https://user-images.githubusercontent.com/69042470/128626463-0da050fd-e438-4be0-8c78-90ca6d756e23.JPG)
![sma_info](https://user-images.githubusercontent.com/69042470/128626503-4babdda2-6b17-46a2-be73-f1041f2627cd.JPG)

**Comment by clasheleander** [comment]
I have also deleted sma and pysma folder from custom_components to make sure im not using any outdated version.

**Comment by clasheleander** [comment]
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by clasheleander** [comment]
Is there any difference between below entities and the others? (with icon "lightning bolt") lightning bolt ones are the only listed in the Energy configuration drop down.
![sma_info_2](https://user-images.githubusercontent.com/69042470/128632430-2e315868-efc2-4d70-b53f-046d6542cecf.JPG)

**Comment by kellerza** [comment]
The lightning ones are only ones that satisfy:

- device_class: energy
- State_class: measurement
- Last_reset: set to some date/time

(you can see this in the dev tools as well)

It is only energy devices (kWh unit) so all seems ok from your screenshots

**Comment by clasheleander** [comment]
Ok.
How can i then add the right entitie, for example "grid_power" to the production config/make it selectable?

Thanks.

**Comment by clasheleander** [comment]
or is it just me who is stupid and has not understood what the new energy function does? :)

**Comment by kellerza** [comment]
Its only energy (kWh) and not power (W / kW) 😉

Or see it as the power units you buy from the electricity grid, which they sell as 1 hour of 1000W

once you have it working you nicely soo how much energy/units you consumed per hour

**Comment by clasheleander** [comment]
I feel so stupid!!! :)
Sorry i took your time!

**Comment by kellerza** [comment]
No worries 👍
